<div id="dbCredentialsForm">
    preparing local installation database..<br>
    <div>
        MySQL server credentials are invalid, please enter correct values...
        <table class="form">
            <tr>
                <td>host</td>
                <td><input name="host" value="<?= html2text($cred->host) ?>"/></td>
            </tr>
            <tr>
                <td>username</td>
                <td><input name="username" value="<?= html2text($cred->username) ?>"/></td>
            </tr>
            <tr>
                <td>password</td>
                <td><input name="password" value="<?= html2text($cred->password) ?>"/></td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <button onclick="
                        deployment.localInstallationDbCred = getInputData('dbCredentialsForm');
                        $id('dbCredentialsForm').remove();
                        deployment.action('localInstallation/m2/db/setCred', 'retry');
                        delete deployment.localInstallationDbCred;
				">Continue
                    </button>
                </td>
            </tr>
        </table>
    </div>
</div>
