<?php $info = $inst->magento->getMaintenanceInfo(); ?>

    <a href="#"
       onclick="form = $id('standardMaintenanceForm'); form.style.display = form.style.display == 'none' ? 'block' : 'none'; return false;">
        Standard Magento maintenance
    </a>
    <div id="standardMaintenanceForm"
         style="padding: 5px; display:<?= $info['standard']['status'] || (!isset($info['customOld']) && !isset($info['customNew'])) ? 'block' : 'none' ?>">
        <span style="color:grey;">(Will show errors/503.php for all)</span>
        <table class="form">
            <tr>
                <td>Status:</td>
                <td><?= $info['standard']['status'] ? '<span style="color: green"><b>On</b></span>' : 'Off' ?></td>
            </tr>
            <tr>
                <td>Allowed IPs:</td>
                <td>
                    <input id="mntIps" type="text" class="wide" value="<?= $inst->vars->get('maintenanceIPs') ?>"/>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <button style="width:140px" onclick="inst.setMaintenance()">Set Maintenance</button>
                    <button
                            onclick="inst.checkMyIP()" <?= Config::getNode('isCentralized') ? "disabled title=\"IP check isn't implemented for central devtool\"" : '' ?>>
                        Check my IP
                    </button>
                    <span id="myIP"></span>
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <button style="width:140px" onclick="inst.unsetMaintenance()">Unset Maintenance</button>
                </td>
            </tr>
        </table>
    </div>

    <div style="height: 10px"></div>

<?php if (isset($info['customOld'])) { ?>

    <b>Custom ISM maintenance v1</b>
    <div id="customOldMaintenanceForm" style="padding: 5px;">
        .htaccess configuration:<br>
        <textarea id="customOldMaintenance"
                  style="width: 100%; background-color: #3465a4; color: #d3d7cf; color:#eee; border:0"
                  spellcheck="false" wrap="off"
                  rows="<?= count($info['customOld']) + 8 ?>"><?= "\n\n\n" . html2text(implode("\n",
                $info['customOld'])) ?></textarea>
        <button onclick="applyCustomOldMaintenance()"> &nbsp; Apply &nbsp;</button>
        <pre style="color:grey">

Use: SetEnv [option] [value]

Options:
  ISMDEV_MAINTANCE (0, 1): active or not
  ISMDEV_MAINTANCE_ALLOWED_IPS (rx list separated by ";"): allowed IP's
  ISMDEV_MAINTANCE_REFRESH_REQUIRED (0, 1): show alert or reload page on ajax request
  ISMDEV_MAINTANCE_ACCESS_CODE (string): allow to come around maintenance by "?maintance_access_code=[string]" in URL
  ISMDEV_MAINTANCE_PAGE: path to maintenance html file
  ISMDEV_MAINTANCE_ALLOWED_URLS: url exception e.g. '/admin'
		</pre>
    </div>

<?php } elseif (isset($info['customNew'])) { ?>

    <b>Custom ISM maintenance v2</b>
    <div id="customNewMaintenanceForm"
         style="padding: 5px; border: 1px solid grey; overflow: hidden; margin-top: 10px; height: 100%">
        <iframe id="customNewMaintenanceIframe" src="<?= $inst->_url ?>dev/?view=maintenance"
                style="width: 100%; height: 750px; border: 0; margin-top: -75px"></iframe>
        <script type="application/javascript">
            function adjustCustomNewMaintenanceIframe() {
                $id('customNewMaintenanceIframe').style.height = document.body.clientHeight - 114;
            }

            adjustCustomNewMaintenanceIframe();
            window.addEventListener('resize', adjustCustomNewMaintenanceIframe);
        </script>
    </div>

<?php } ?>