<br>
<?php if ($changes === false) { ?>
    <span style="color:red; white-space: pre;"><?= html2text($error) ?></span>
<?php } elseif (!count($changes)) { ?>
    No changes were deployed
<?php } else { ?>
    <?php if (count($depins)) { ?>
        <?php foreach ($depins as $depin) { ?>
            <?php
            $message = $depin['isNew'] ?
                'New instruction has been deployed: ' . $depin['name']
                : 'Deployment instruction has been changed by ' . $depin['author'] . ': ' . $depin['name']
            ?>
            <?= template('message/notice', array('message' => $message)); ?>
        <?php } ?>
    <?php } ?>
    <table cellpadding="0" cellspacing="0" class="deployed-changes">
        <?php foreach ($changes as $change) { ?>
            <tr class='change-type-<?= $change['type'] ?>'>
                <td><?= $change['type'] ?></td>
                <td><?= $change['file'] ?></td>
            </tr>
        <?php } ?>
    </table>
    <?php if ($changesLimitExceeded) { ?>
        ... limit of changes in <?= html2text($changesLimit) ?> lines exceeded
    <?php } ?>
<?php } ?>
