<?php if ($inst->project->type === 'magento2') { ?>
    Not implemented for Magento 2 yet
    <?php return; ?>
<?php } ?>
<?php $credentials = $inst->getDbCredentials(); ?>
<div style="position: absolute; top: 110px; left: 0; width: 100%; height: calc(100% - 115px); background-color: white;">
    <iframe src="/Magento_Database_Cleaner?
			db_host=<?= urlencode($credentials->host) ?>
			&db_user=<?= urlencode($credentials->username) ?>
			&db_pass=<?= urlencode($credentials->password) ?>
			&db_name=<?= urlencode($credentials->dbname) ?>"
            style="width: 100%; height: 100%; border:0">
    </iframe>
</div>
