<?php $cred = $inst->getDbCredentials() ?>

<table class="list">
    <?php foreach ($cred as $key => $value) { ?>
        <tr>
            <td><b><?= html2text(ucfirst($key)) ?></b>:</td>
            <td><?= html2text($value) ?></td>
        </tr>
    <?php } ?>
</table>
<br>
<b>mysql</b> connection string:<br>
<textarea class="connection-string" type="text" readonly="readonly" rows="1" wrap="off"
          style="margin-left: 0"
> <?=
    preg_replace(
        '~ 2>&1$~', '',
        cmd(
            'MYSQL_PWD=%s mysql -h%s -u%s %s',
            $cred->password, $cred->host, $cred->username, $cred->dbname
        )
    )
    ?></textarea>
<br>
<b>mysqldump</b> connection string:<br>
<textarea class="connection-string" type="text" readonly="readonly" rows="1" wrap="off"
          style="margin-left: 0"
> <?=
    preg_replace(
        '~ 2>&1$~', '',
        cmd(
            'MYSQL_PWD=%s mysqldump -h%s -u%s %s',
            $cred->password, $cred->host, $cred->username, $cred->dbname
        )
    )
    ?></textarea>
