<?php
/** @var \Project\Installation $inst */
$data = $inst->getDbCredentials('app');
?>
<div id="dbCredentialsForm">
    Database credentials are invalid, please enter correct values...
    <table class="form">
        <tr>
            <td>host</td>
            <td><input name="host" value="<?= html2text($data->host) ?>"/></td>
        </tr>
        <tr>
            <td>username</td>
            <td><input name="username" value="<?= html2text($data->username) ?>"/></td>
        </tr>
        <tr>
            <td>password</td>
            <td><input name="password" value="<?= html2text($data->password) ?>"/></td>
        </tr>
        <tr>
            <td>dbname</td>
            <td><input name="dbname" value="<?= html2text($data->dbname) ?>"/></td>
        </tr>
        <tr>
            <td></td>
            <td>
                <button onclick="
					$id('dbCredMessages').innerHTML = '';
					inst.action('setDbCredentials', getInputData('dbCredentialsForm'), onSetDbCredentialsSuccess);
				">Continue
                </button>
            </td>
        </tr>
        <tr>
            <td></td>
            <td colspan="2">
                <div id="dbCredMessages"></div>
            </td>
        </tr>
    </table>
</div>

<script>
    onSetDbCredentialsSuccess = function (response) {
        if (response === true) {
            $id('dbCredentialsForm').remove();
            installer.addMessage('done');
            installer.install();
        } else {
            $id('dbCredMessages').innerHTML = response;
        }
    }
</script>