<head>
    <title><?= html2text(page()->title) ?></title>
    <link rel="stylesheet" type="text/css" href="/app/skin/popup.css?v=<?= time() ?>" media="all"/>
    <script type="application/javascript" src="/app/js/functions.js?v=<?= time() ?>"></script>
    <script type="application/javascript" src="/app/js/popup.js?v=<?= time() ?>"></script>
    <script type="application/javascript" src="/app/js/init.js?v=<?= time() ?>"></script>

    <!-- Codemirror -->
    <link rel="stylesheet" href="/app/js/codemirror-5.11/lib/codemirror.css">
    <link rel="stylesheet" href="/app/js/codemirror-5.11/addon/hint/show-hint.css">
    <script src="/app/js/codemirror-5.11/lib/codemirror.js"></script>
    <script src="/app/js/codemirror-5.11/addon/hint/show-hint.js"></script>
    <script src="/app/js/codemirror-5.11/addon/hint/sql-hint.js"></script>
    <script src="/app/js/codemirror-5.11/keymap/sublime.js"></script>
    <script src="/app/js/codemirror-5.11/mode/sql/sql.js"></script>
    <script src="/app/js/codemirror-5.11/mode/shell/shell.js"></script>
    <script src="/app/js/codemirror-5.11/mode/clike/clike.js"></script>
    <script src="/app/js/codemirror-5.11/mode/php/php.js"></script>
    <script src="/app/js/codemirror-5.11/mode/ism/TE.js?v=<?= time() ?>"></script>
    <script src="/app/js/codemirror-5.11/addon/comment/comment.js"></script>
    <script src="/app/js/codemirror-5.11/addon/comment/continuecomment.js"></script>

    <link rel="stylesheet" type="text/css" href="/app/skin/all.css?v=<?= time() ?>" media="all"/>

</head>