<div id="popup-wrapper-table">
    <div id="popup-wrapper-cell">
        <div id="popup">
            <div class="popup-content-wrapper">
                <div id="popup.content"></div>
            </div>
            <div class="buttons">
                <button id="popup.button.cancel">Cancel</button>
                <button id="popup.button.ok">OK</button>
            </div>
        </div>
    </div>
</div>
